[package]
name = "idpoolrs"
version = "0.1.0"
authors = ["denvercoder21 <github@ottair.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
